// actojs — Core types
// Web runtime: cooperative event-loop scheduler.

/** Unique process identifier. Generated by the actor system at spawn time. */
export type PID = string;
/** Opaque reference token, typically used for monitor or timer identifiers. */
export type Ref = symbol;
/** Destination for sending messages — either a raw PID or a registered name. */
export type Dest = PID | string;
/** Spawn option: link or monitor the spawned process to the caller. */
export type SpawnOpt = "link" | "monitor";

/**
 * Per-process resource limits for fault isolation.
 * Set at spawn() time or via Process.flag() at runtime.
 * All fields default to 0 (unlimited / disabled).
 */
export interface ProcessLimits {
  // Maximum messages to process before yielding to the event loop.
  // A yield point lets other actors run and triggers a memory check.
  // 0 disables the budget — the actor yields only on await points.
  messageBudget?: number;
  // Maximum mailbox items. When exceeded, incoming messages are
  // dropped and a SYSTEM alert is delivered instead.
  // 0 = unlimited (default).
  maxMailboxSize?: number;
  // Per handle_call/handle_cast timeout in milliseconds.
  // When exceeded, the caller gets an error and the process
  // accumulates a timeout counter. 3 timeouts = process exit.
  // 0 = no timeout (default).
  execTimeout?: number;
  // Maximum RSS memory in bytes for this process. Checked at
  // yield points. When exceeded, a SYSTEM alert is delivered.
  // Requires process.memoryUsage() (Node / Bun). Ignored in browsers.
  // 0 = no limit (default).
  maxMemory?: number;
}

// Spawn options object (alternative to SpawnOpt[]).
export interface SpawnOptions {
  link?: boolean;
  monitor?: boolean;
  limits?: ProcessLimits;
  /** When true, delegates to the active WorkerRuntime for true parallelism.
   *  Defaults to false (cooperative scheduling). */
  worker?: boolean;
}

/**
 * Generic module reference: any object whose keys map to callable functions.
 * Used by MFA tuples to dispatch function calls by name at runtime.
 */
export type Module = Record<string, unknown>;
/** Module-Function-Arguments tuple for dynamic dispatch at spawn time. */
export type MFA = [Module, string, unknown[]];

/** Message delivered to monitors when a monitored process exits. */
export interface DownMessage {
  type: "DOWN";
  ref: Ref;
  pid: PID;
  reason: unknown;
}

/** Snapshot of a process's public state for introspection and debugging. */
export interface ProcessInfo {
  status: "running" | "alive" | "exiting" | "exited";
  messageQueueLength: number;
  maxMailboxSize: number;
  messageBudget: number;
  messageCount: number;
  execTimeout: number;
  execTimeoutCount: number;
  maxMemory: number;
  links: PID[];
  monitors: { ref: Ref; pid: PID }[];
  monitoredBy: { pid: PID; ref: Ref[] }[];
  trapExit: boolean;
  registeredName: string | null;
}

/** Result returned by start/start_link: either an ok PID or an error. */
export type OnStart = { ok: PID } | { error: Error };
/** Result returned by start_child: either an ok PID or an error. */
export type OnStartChild = { ok: PID } | { error: Error };

/**
 * Supervisor restart strategy:
 * - `one_for_one` — only the failed child is restarted.
 * - `one_for_all` — all children are restarted when any fails.
 * - `rest_for_one` — the failed child and all children started after it are restarted.
 */
export type Strategy = "one_for_one" | "one_for_all" | "rest_for_one";

/** Specification for a static child managed by a supervisor. */
export interface ChildSpec {
  id: string;
  start: MFA; // [module, functionName, args]
  restart?: "permanent" | "transient" | "temporary";
  shutdown?: number | "brutal_kill" | "infinity";
  type?: "worker" | "supervisor";
  significant?: boolean;
}

/** Runtime information about a running child process. */
export interface ChildInfo {
  id: string | undefined;
  pid: PID;
  type: "worker" | "supervisor";
  modules: Module[];
}

/** Aggregate counts of supervisor children by category. */
export interface Counts {
  specs: number;
  active: number;
  supervisors: number;
  workers: number;
}

/** Handle for awaiting or yielding a task's result. */
export interface TaskHandle<R> {
  pid: PID;
  ref: Ref;
}

/** Key registration mode for the process registry. */
export type RegistryKeyMode =
  "unique" | "duplicate" | { duplicate: "key" } | { duplicate: "pid" };

/** Options for starting a process registry. */
export interface RegistryStartOptions {
  keys: RegistryKeyMode;
  name?: string;
  partitions?: number;
  listeners?: string[];
  meta?: Record<string, unknown>;
}

/** Options for starting a supervisor (strategy, restart limits, name). */
export interface SupervisorStartOptions {
  strategy: Strategy;
  name?: string;
  max_restarts?: number;
  max_seconds?: number;
}

/** Extended supervisor options for module-based init (max_children, extra_arguments). */
export interface SupervisorInitOptions extends SupervisorStartOptions {
  max_children?: number;
  extra_arguments?: unknown[];
}

/** Complete supervisor specification returned by a module's init callback. */
export interface SupervisorSpec {
  children: ChildSpec[];
  strategy: Strategy;
  max_restarts: number;
  max_seconds: number;
  max_children: number;
  extra_arguments: unknown[];
}

/** Options for starting a distributed node. */
export interface NodeStartOpts {
  name_domain?: "shortnames" | "longnames";
}

/**
 * Visibility state of a remote node in the cluster.
 * - `visible` — the local node itself.
 * - `hidden` — a known node that is not automatically discovered.
 * - `connected` — an actively connected remote node.
 * - `this` — used as a filter value to refer to the local node.
 * - `known` — a previously connected node.
 */
export type NodeState = "visible" | "hidden" | "connected" | "this" | "known";
